set guifont=Inconsolata-dz\ for\ Powerline:h15
set gcr=a:blinkon0
set lines=34
set columns=134
set fuoptions=maxvert,maxhorz
set guitablabel=%t

set guioptions-=T
"kill toolbar
set guioptions-=r
"kill right scrollbar
set guioptions-=R
set guioptions-=l
"kill left scrollbar
set guioptions-=L

"map command-arrow to move around splits
noremap <D-up> <C-W><up>
noremap <D-down> <C-W><down>
noremap <D-left> <C-W><left>
noremap <D-right> <C-W><right>

noremap <C-k> <C-W><up>
noremap <C-j> <C-W><down>
noremap <C-h> <C-W><left>
noremap <C-l> <C-W><right>
