" Vimrc
" David Zhou
set nocompatible
filetype on "os x needs this sometimes. don't ask. its a mystery
filetype off "required for neobundle
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle/
endif
let $GIT_SSL_NO_VERIFY = 'true' " required for bad ssl certs
let g:neobundle#log_filename = '' " don't spit out to logfile
call neobundle#rc(expand('~/.vim/installed/')) " gitignore is on for /installed, so use that instead of default bundle dir
" required!
" let neobundle manage neobundle
NeoBundleFetch 'Shougo/neobundle.vim'

" Recommended to install
" After install, turn shell ~/.vim/bundle/vimproc, (n,g)make -f your_machines_makefile
NeoBundle 'Shougo/vimproc'


" BUNDLES
NeoBundle 'vim-scripts/L9.git'
NeoBundle 'Lokaltog/vim-powerline'
NeoBundle 'mileszs/ack.vim'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tpope/vim-unimpaired'
NeoBundle 'sjbach/lusty'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'scrooloose/nerdcommenter'
NeoBundle 'Raimondi/delimitMate'
NeoBundle 'vim-scripts/IndexedSearch'
NeoBundle 'vim-scripts/matchit.zip'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'sjl/gundo.vim'
NeoBundle 'vim-scripts/YankRing.vim'
NeoBundle 'nathanaelkane/vim-indent-guides'
" GIT SHIT
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'int3/vim-extradite'

" HTML/CSS
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'groenewege/vim-less'
NeoBundle 'tpope/vim-haml'
NeoBundle 'tudorprodan/html_annoyance.vim'

" Javascript
NeoBundle 'pangloss/vim-javascript'

" Ruby/Rails
NeoBundle 'tpope/vim-rails.git'
NeoBundle 'tpope/vim-endwise'
NeoBundle 'tpope/vim-rvm'


" Now that vundle has finished its thing
" turn filetype back on
filetype plugin indent on

if neobundle#exists_not_installed_bundles()
  echomsg 'Not installed bundles : ' .
        \ string(neobundle#get_not_installed_bundle_names())
  echomsg 'Please execute ":NeoBundleInstall" command.'
  "finish
endif

set background=dark
color ir_black
syntax on
set shm=atI "disable intro screen
set ttyfast " Improves redrawing for newer computers
set mouse=a
scriptencoding utf-8
set virtualedit=onemore
set history=1000
set nofoldenable " disable code folding
set display=lastline,uhex
set switchbuf=useopen

set backup
set backupdir=$HOME/.vimbackup//
set directory=$HOME/.vimswap//
" Create directories if they don't exist
silent execute '!mkdir -p $HOME/.vimbackup'
silent execute '!mkdir -p $HOME/.vimswap'

"typos sucks
command! -bang -nargs=* W w<bang> <args>
command! -bang -nargs=* Q q<bang> <args>
command! -bang -nargs=* Wq wq<bang> <args>
command! -bang -nargs=* WQ wq<bang> <args>

set showmode " display the current mode
set showcmd
set wildmode=longest,list,full
set wildmenu
set completeopt=menu

set wildignore+=*.o,*.fasl,CVS,*.pyc,._*,.DS_Store,*~,*.gif,*.jpg,*.png,*.pdf,*.psd,*.svn,.svn,.git,.hg

set ruler
set number
set nuw=4
set vb "set visual bell
set binary noeol
set backspace=indent,eol,start
set laststatus=2
set showmatch

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set bs=2

"change softwrap to sane setting
set wrap linebreak textwidth=0

"set mapleader
let mapleader = ","
let g:mapleader = ","

" allow buffers to be fully squashed
set winminheight=0
set hidden

nnoremap ' `
nnoremap ` '

" Remap control-g to esc
map <C-g> <esc>
noremap <C-g> <esc>

"scrolling offset
set scrolloff=5
set shortmess=atI

"turn off middleclicking
noremap <MiddleMouse> <LeftMouse>
noremap <2-MiddleMouse> <LeftMouse>
noremap <3-MiddleMouse> <LeftMouse>
noremap <4-MiddleMouse> <LeftMouse>

"Set to auto read when a file is changed from the outside
set autoread

" sudo write
map w! w !sudo tee % >/dev/null

" if i indent in visual mode, i want to remain in visual mode
vnoremap < <gv
vnoremap > >gv

"map control/command arrows for moving between windows
map <C-up> <C-W><up>
map <C-down> <C-W><down>
map <C-left> <C-W><left>
map <C-right> <C-W><right>
"these should ideally be in gvimrc; duplicated there
noremap <D-up> <C-W><up>
noremap <D-down> <C-W><down>
noremap <D-left> <C-W><left>
noremap <D-right> <C-W><right>

"map window manipulation to match emacs
noremap <D-1> :only<cr>
noremap <D-0> :close<cr>
noremap <D-2> :sp<cr>
noremap <D-3> :vsp<cr>
noremap! <D-1> <esc>:only<cr>
noremap! <D-0> <esc>:close<cr>
noremap! <D-2> <esc>:sp<cr>
noremap! <D-3> <esc>:vsp<cr>

command! SmartHomeKey call SmartHomeKey()
function! SmartHomeKey()
  let l:lnum	=	line('.')
  let l:ccol	=	col('.')
  execute 'normal! ^'
  let l:fcol	=	col('.')
  execute 'normal! 0'
  let l:hcol	=	col('.')
  if l:ccol != l:fcol
    call cursor(l:lnum, l:fcol)
  else
    call cursor(l:lnum, l:hcol)
  endif
endfun

" map CTRL-E to end-of-line (insert mode)
map <C-e> <esc>$<right><esc>
imap <C-e> <esc>$i<right>
" map CTRL-A to beginning-of-line (insert mode)
map <C-a> <esc>:SmartHomeKey<CR><esc>
imap <C-a> <esc>:SmartHomeKey<CR>i

ab teh the
ab fro for

set incsearch
set ignorecase
set wrapscan
set smartcase

"No scrollbars
set guioptions-=L
set guioptions-=l
set guioptions-=R
set guioptions-=r

"easily equalize windows with plus
nmap + <c-w>=

"tab key in normal mode autoindents
nmap <tab> ==
"if we rebind tab though, we need to also rebind <C-i> to something else
"so we can still use the jumplist
nnoremap <C-p> <C-i>

"fast file switching
map <C-q> <esc>:b#<esc>
nmap <C-q> <esc>:b#<cr>
noremap <C-q> <esc>:b#<cr>
noremap! <C-q> <esc>:b#<cr>

map <Leader>t :NERDTreeToggle<cr>
map <Leader>m :NERDTreeToggle<cr>

nmap <silent> <Leader>, :CtrlP<cr>
nmap <silent> <Leader>r :CtrlPClearCache<cr>
noremap <D-e> :CtrlP<cr>
noremap! <D-e> <esc>:CtrlP<cr>
noremap <D-E> :CtrlPClearCache<cr>
noremap! <D-E> <esc>:CtrlPClearCache<cr>

noremap <D-b> :CtrlPBuffer<cr>
noremap! <D-b> <esc>:CtrlPBuffer<cr>

noremap <D-r> :CtrlPMRU<cr>
noremap! <D-r> <esc>:CtrlPMRU<cr>

nmap <Leader>/ :LustyFilesystemExplorerFromHere<cr>
nmap <leader>. :LustyFilesystemExplorer<cr>
nmap <D-o> :LustyFilesystemExplorer<cr>

" NerdTree options
let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1

" Fugitive options
" if a fugitive buffer is hidden, just go ahead and delete it
autocmd BufReadPost fugitive://* set bufhidden=delete

"CommandT options
let g:CommandTMaxFiles=10000
let g:CommandTMaxHeight=10
let g:CommandTMatchWindowReverse=1

"CtrlP options
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_mruf_case_sensitive = 0
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'
let g:ctrlp_cache_dir = $HOME.'/.cache/ctrlp'
let g:ctrlp_mruf_max = 2000
let g:ctrlp_mruf_exclude = '/tmp/.*\|/temp/.*|/var/folders' " MacOSX/Linux
let g:ctrlp_dont_split = 'Help'
let g:ctrlp_extensions = ['tag', 'quickfix', 'undo']
" press control-v instead of enter to open buffer in existing window
let g:ctrlp_switch_buffer = 'v'
let g:ctrlp_prompt_mappings = {
    \ 'PrtSelectMove("j")':   ['<c-j>', '<c-n>'],
    \ 'PrtSelectMove("k")':   ['<c-k>', '<c-p>'],
    \ 'PrtHistory(-1)':       ['<down>'],
    \ 'PrtHistory(1)':        ['<up>'],
    \ 'PrtClearCache()':      ['<F5>', '<c-r>'],
    \ }

" Tagbar options
noremap <leader>o :TagbarToggle<CR>
noremap <D-d> :TagbarToggle<CR>
noremap! <D-d> <esc>:TagbarToggle<cr>
set tags=tags,.git/tags,TAGS
let g:tagbar_compact = 1
let g:tagbar_autoshowtag = 1
let g:tagbar_autoclose = 1
let g:tagbar_type_coffee = {
  \ 'kinds' : [
  \   'f:functions',
  \   'o:object'
  \ ],
  \ 'kind2scope' : {
  \  'f' : 'object',
  \   'o' : 'object'
  \},
  \ 'sro' : ".",
  \ 'ctagsbin' : 'coffeetags',
  \ 'ctagsargs' : '--include-vars '
  \}
let g:tagbar_type_markdown = {
  \ 'ctagstype' : 'markdown',
  \ 'kinds' : [
    \ 'h:Heading_L1',
    \ 'i:Heading_L2',
    \ 'k:Heading_L3'
  \ ]
\ }
let g:tagbar_type_ruby = {
    \ 'kinds' : [
        \ 'm:modules',
        \ 'c:classes',
        \ 'd:describes',
        \ 'C:contexts',
        \ 'f:methods',
        \ 'F:singleton methods'
    \ ]
\ }

"vim indent guide options
let g:indent_guides_enable_on_vim_startup = 1

let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 1

"yankring options
let g:yankring_enabled = 1
let g:yankring_max_history = 1000
let g:yankring_max_display = 100
let g:yankring_ignore_duplicate = 1

"Supertab options
let g:SuperTabDefaultCompletionType = "context"

"Gundo options
nnoremap <leader>u :GundoToggle<CR>

" OmniComplete options
set completeopt=menuone
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Define a command to make it easier to use
command! -nargs=+ QFDo call QFDo(<q-args>)
" Function that does the work
function! QFDo(command)
    " Create a dictionary so that we can
    " get the list of buffers rather than the
    " list of lines in buffers (easy way
    " to get unique entries)
    let buffer_numbers = {}
    " For each entry, use the buffer number as
    " a dictionary key (won't get repeats)
    for fixlist_entry in getqflist()
        let buffer_numbers[fixlist_entry['bufnr']] = 1
    endfor
    " Make it into a list as it seems cleaner
    let buffer_number_list = keys(buffer_numbers)

    " For each buffer
    for num in buffer_number_list
        " Select the buffer
        exe 'buffer' num
        " Run the command that's passed as an argument
        exe a:command
        " Save if necessary
        update
    endfor
endfunction

command! -nargs=0 -bar Qargs execute 'args ' . QuickfixFilenames()
function! QuickfixFilenames()
  " Building a hash ensures we get each buffer only once
  let buffer_numbers = {}
  for quickfix_item in getqflist()
    let buffer_numbers[quickfix_item['bufnr']] = bufname(quickfix_item['bufnr'])
  endfor
  return join(values(buffer_numbers))
endfunction

" strip whitespace
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

"ensure no tabs
autocmd BufWritePre * :set expandtab

"diffing is better in tabs in order to preserve window layout
command! GdiffInTab tabedit %|Gdiff

" LANGUAGE OPTIONS
"
"syntax color options for various languages
"syntax coloring for apache log files
autocmd BufRead,BufNewFile *access.log* set filetype=httplog

autocmd BufRead,BufNewFile *.tumblr.html setfiletype=tumblr

" these are all html really
autocmd BufRead,BufNewFile *.ss set filetype=html
autocmd BufRead,BufNewFile *.fbml set filetype=html
autocmd BufRead,BufNewFile *.lbi set filetype=html
autocmd BufRead,BufNewFile *.dtpl set filetype=html

"Google Go
autocmd BufRead,BufNewFile *.go set filetype=go

"LOLCODE
autocmd BufRead,BufNewFile *.lol set filetype=lolcodtpl

"I edit actionscript files, not atlas files, whatever the hell they are
autocmd BufRead,BufNewFile *.as set filetype=actionscript

"Json is still javascript
au BufNewFile,BufRead  *.json set filetype=javascript

"language specific options
"PHP
let php_sql_query=1
let php_baselib=1
let php_htmlInStrings=1
let PHP_BracesAtCodeLevel = 0
let PHP_removeCRwhenUnix = 1
let php_noShortTags = 1

"HTML
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
"matchtagalways
let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'jinja' : 1,
    \ 'eruby': 1
    \}

"Python
let g:pyflakes_user_quickfix = 0
autocmd BufRead,BufNewFile *.py set autoindent
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,with,try,except,finally,def,class

"Ruby

"CSS

"Javascript
" Use Node.js for JavaScript interpretation
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"

