" Vimrc
" David Zhou

set nocompatible
filetype on "os x needs this sometimes. don't ask. its a mystery
filetype off "required for neobundle
let $GIT_SSL_NO_VERIFY = 'true' " required for bad ssl certs
set runtimepath+=/usr/local/bin

call plug#begin('~/.vim/installed')

call dein#begin(expand('~/.vim/installed')) " gitignore is on for /installed, so use that instead of default bundle dir

" Core stuff
call dein#add('vim-scripts/L9.git')
call dein#add('qpkorr/vim-bufkill')
call dein#add('Lokaltog/vim-easymotion')
call dein#add('tpope/vim-surround')
call dein#add('tpope/vim-unimpaired')
call dein#add('Raimondi/delimitMate')
call dein#add('henrik/vim-indexed-search')
call dein#add('vim-scripts/matchit.zip')
call dein#add('sjl/gundo.vim')
call dein#add('vim-scripts/YankRing.vim')
call dein#add('nathanaelkane/vim-indent-guides')
call dein#add('tpope/vim-eunuch')
call dein#add('jaxbot/semantic-highlight.vim')

" Javascript
call dein#add('othree/yajs.vim')

" HTML/CSS
call dein#add('kchmck/vim-coffee-script')
call dein#add('groenewege/vim-less')
call dein#add('tpope/vim-haml')
call dein#add('tudorprodan/html_annoyance.vim')

" Ruby/Rails
call dein#add('tpope/vim-rails.git')
call dein#add('tpope/vim-endwise')

filetype plugin indent on

set background=dark
color ir_black
syntax on
set shm=atI "disable intro screen
set ttyfast " Improves redrawing for newer computers
set mouse=a
scriptencoding utf-8
set encoding=utf-8
set virtualedit=onemore
set history=1000
set nofoldenable " disable code folding
set display=lastline,uhex
set switchbuf=useopen

set backup
set backupdir=$HOME/.vimbackup//
set directory=$HOME/.vimswap//
" Create directories if they don't exist
silent execute '!mkdir -p $HOME/.vimbackup'
silent execute '!mkdir -p $HOME/.vimswap'

"typos sucks
command! -bang -nargs=* W w<bang> <args>
command! -bang -nargs=* Q q<bang> <args>
command! -bang -nargs=* Wq wq<bang> <args>
command! -bang -nargs=* WQ wq<bang> <args>

set showmode " display the current mode
set showcmd
set wildmode=longest,list,full
set wildmenu
set completeopt=menu

set wildignore+=*.o,*.fasl,CVS,*.pyc,._*,.DS_Store,*~,*.gif,*.jpg,*.png,*.pdf,*.psd,*.svn,.svn,.git,.hg

set ruler
set number
set nuw=4
set vb "set visual bell
set backspace=indent,eol,start
set laststatus=2
set showmatch

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set bs=2

"change softwrap to sane setting
set wrap linebreak textwidth=0

"set mapleader
let mapleader = ","
let g:mapleader = ","

" allow buffers to be fully squashed
set winminheight=0
set hidden

nnoremap ' `
nnoremap ` '

" Remap control-g to esc
map <C-g> <esc>
noremap <C-g> <esc>

"scrolling offset
set scrolloff=5
set shortmess=atI

"turn off middleclicking
noremap <MiddleMouse> <LeftMouse>
noremap <2-MiddleMouse> <LeftMouse>
noremap <3-MiddleMouse> <LeftMouse>
noremap <4-MiddleMouse> <LeftMouse>

"Set to auto read when a file is changed from the outside
set autoread

" sudo write
map w! w !sudo tee % >/dev/null

" if i indent in visual mode, i want to remain in visual mode
vnoremap < <gv
vnoremap > >gv

"map control/command arrows for moving between windows
map <C-up> <C-W><up>
map <C-down> <C-W><down>
map <C-left> <C-W><left>
map <C-right> <C-W><right>
"these should ideally be in gvimrc; duplicated there
noremap <D-up> <C-W><up>
noremap <D-down> <C-W><down>
noremap <D-left> <C-W><left>
noremap <D-right> <C-W><right>

"map window manipulation to match emacs
noremap <D-1> :only<cr>
noremap <D-0> :close<cr>
noremap <D-2> :sp<cr>
noremap <D-3> :vsp<cr>
noremap! <D-1> <esc>:only<cr>
noremap! <D-0> <esc>:close<cr>
noremap! <D-2> <esc>:sp<cr>
noremap! <D-3> <esc>:vsp<cr>

command! SmartHomeKey call SmartHomeKey()
function! SmartHomeKey()
  let l:lnum	=	line('.')
  let l:ccol	=	col('.')
  execute 'normal! ^'
  let l:fcol	=	col('.')
  execute 'normal! 0'
  let l:hcol	=	col('.')
  if l:ccol != l:fcol
    call cursor(l:lnum, l:fcol)
  else
    call cursor(l:lnum, l:hcol)
  endif
endfun

" map CTRL-E to end-of-line (insert mode)
map <C-e> <esc>$<right><esc>
imap <C-e> <esc>$i<right>
" map CTRL-A to beginning-of-line (insert mode)
map <C-a> <esc>:SmartHomeKey<CR><esc>
imap <C-a> <esc>:SmartHomeKey<CR>i

ab teh the
ab fro for

set incsearch
set ignorecase
set wrapscan
set smartcase

"No scrollbars
set guioptions-=L
set guioptions-=l
set guioptions-=R
set guioptions-=r

"easily equalize windows with plus
nmap + <c-w>=

"tab key in normal mode autoindents
nmap <tab> ==
"if we rebind tab though, we need to also rebind <C-i> to something else
"so we can still use the jumplist
nnoremap <C-p> <C-i>

"fast file switching
map <C-q> <esc>:b#<esc>
nmap <C-q> <esc>:b#<cr>
noremap <C-q> <esc>:b#<cr>
noremap! <C-q> <esc>:b#<cr>

map <Leader>t :NERDTreeToggle<cr>
map <Leader>m :NERDTreeToggle<cr>
map <Leader><Leader> :NERDTreeToggle
" open nerdtree focused on the existing file
map <Leader>n :NERDTreeFind<cr>
noremap <D-O> :NERDTreeToggle<CR>
noremap! <D-O> <esc>:NERDTreeToggle<cr>
noremap <D-M> :NERDTreeFind<CR>
noremap! <D-M> <esc>:NERDTreeFind<cr>
noremap <D-N> :NERDTreeFind<CR>
noremap! <D-N> <esc>:NERDTreeFind<cr>
noremap <D-A> :NERDTreeFind<CR>
noremap! <D-A> <esc>:NERDTreeFind<cr>

" Quickly open/reload vim
nnoremap <leader>ev :e $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

"Unite options
let g:unite_source_history_yank_enable = 1
call unite#filters#matcher_default#use(['matcher_glob'])
nnoremap <D-b> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=buffer  -start-insert file_mru buffer<cr>
nnoremap <D-r> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=mru     -start-insert file_mru<cr>
nnoremap <D-e> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=files   -start-insert file_rec/async:!<cr>
nnoremap <D-t> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=files   -start-insert file_rec/async:!<cr>
nnoremap <D-d> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=outline -start-insert outline<cr>
nnoremap <D-y> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=yank    history/yank<cr>
nnoremap <D-F> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=search  -start-insert grep:.<cr>
nnoremap <D-l> :<C-u>Unite -no-cursor-line -no-empty -no-split -buffer-name=line -start-insert line<cr>
nnoremap <D-f> :<C-u>Unite -no-cursor-line -no-empty -quick-match buffer<cr>

if executable('ag')
	let g:unite_source_grep_command='ag'
	let g:unite_source_grep_default_opts='--nocolor --line-numbers --nogroup -S -C4'
	let g:unite_source_grep_recursive_opt=''
  let g:unite_source_rec_async_command = [ 'ag', '-l', '-g', '', '--nocolor' ]
elseif executable('ack')
	let g:unite_source_grep_command='ack'
	let g:unite_source_grep_default_opts='--no-heading --no-color -C4'
	let g:unite_source_grep_recursive_opt=''
endif

function! s:unite_settings()
  nmap <buffer> Q <plug>(unite_exit)
  nmap <buffer> <esc> <plug>(unite_exit)
  imap <buffer> <esc> <plug>(unite_exit)
endfunction
autocmd FileType unite call s:unite_settings()

"vim-airline options
let g:airline_enable_branch=1
let g:airline_branch_empty_message=''
let g:airline_detect_modified=1
let g:airline_inactive_collapse=1
let g:airline_theme='molokai'
let g:airline_powerline_fonts=1

"NERDTree options
let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1
let NERDTreeWinSize=51
let NERDTreeQuitOnOpen=1

" Fugitive options
" if a fugitive buffer is hidden, just go ahead and delete it
autocmd BufReadPost fugitive://* set bufhidden=delete

" Syntastic options
let g:syntastic_check_on_open=1

" YouCompleteMe options
let g:ycm_add_preview_to_completeopt=0
let g:ycm_confirm_extra_conf=0
set completeopt-=preview

"vim indent guide options
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 1

"yankring options
let g:yankring_enabled = 1
let g:yankring_max_history = 1000
let g:yankring_max_display = 100
let g:yankring_ignore_duplicate = 1

"Supertab options
let g:SuperTabDefaultCompletionType = "context"

"Gundo options
nnoremap <leader>u :GundoToggle<CR>

"bufkill options
let g:BufKillActionWhenBufferDisplayedInAnotherWindow = "kill"
let g:BufKillActionWhenModifiedFileToBeKilled = "fail"
let g:BufKillCreateMappings = 0
noremap <D-k> :BD<CR>
noremap! <D-k> <esc>:BD<cr>

" OmniComplete options
set completeopt=menuone

" Define a command to make it easier to use
command! -nargs=+ QFDo call QFDo(<q-args>)
" Function that does the work
function! QFDo(command)
    " Create a dictionary so that we can
    " get the list of buffers rather than the
    " list of lines in buffers (easy way
    " to get unique entries)
    let buffer_numbers = {}
    " For each entry, use the buffer number as
    " a dictionary key (won't get repeats)
    for fixlist_entry in getqflist()
        let buffer_numbers[fixlist_entry['bufnr']] = 1
    endfor
    " Make it into a list as it seems cleaner
    let buffer_number_list = keys(buffer_numbers)

    " For each buffer
    for num in buffer_number_list
        " Select the buffer
        exe 'buffer' num
        " Run the command that's passed as an argument
        exe a:command
        " Save if necessary
        update
    endfor
endfunction

command! -nargs=0 -bar Qargs execute 'args ' . QuickfixFilenames()
function! QuickfixFilenames()
  " Building a hash ensures we get each buffer only once
  let buffer_numbers = {}
  for quickfix_item in getqflist()
    let buffer_numbers[quickfix_item['bufnr']] = bufname(quickfix_item['bufnr'])
  endfor
  return join(values(buffer_numbers))
endfunction

" strip whitespace
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

"ensure no tabs
autocmd BufWritePre * :set expandtab

"diffing is better in tabs in order to preserve window layout
command! GdiffInTab tabedit %|Gdiff

" LANGUAGE OPTIONS
"
"syntax color options for various languages
"
"syntax coloring for apache log files
autocmd BufRead,BufNewFile *access.log* set filetype=httplog
autocmd BufRead,BufNewFile *.tumblr.html setfiletype=tumblr

" these are all html really
autocmd BufRead,BufNewFile *.ss set filetype=html
autocmd BufRead,BufNewFile *.fbml set filetype=html
autocmd BufRead,BufNewFile *.lbi set filetype=html
autocmd BufRead,BufNewFile *.dtpl set filetype=html

"Google Go
autocmd BufRead,BufNewFile *.go set filetype=go

"LOLCODE
autocmd BufRead,BufNewFile *.lol set filetype=lolcodtpl

"I edit actionscript files, not atlas files, whatever the hell they are
autocmd BufRead,BufNewFile *.as set filetype=actionscript

"Json is still javascript
au BufNewFile,BufRead  *.json set filetype=javascript


"language specific options
"
"PHP
let php_sql_query=1
let php_baselib=1
let php_htmlInStrings=1
let PHP_BracesAtCodeLevel = 0
let PHP_removeCRwhenUnix = 1
let php_noShortTags = 1

"Python
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
let g:pyflakes_user_quickfix = 0
autocmd BufRead,BufNewFile *.py set autoindent
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,with,try,except,finally,def,class

"Ruby
let g:tagbar_type_ruby = {
    \ 'kinds' : [
        \ 'm:modules',
        \ 'c:classes',
        \ 'd:describes',
        \ 'C:contexts',
        \ 'f:methods',
        \ 'F:singleton methods'
    \ ]
\ }

"HTML
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
"matchtagalways
let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'jinja' : 1,
    \ 'eruby': 1
    \}

"CSS
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS

"Javascript
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
" Use Node.js for JavaScript interpretation
let javascript_enable_domhtmlcss=1
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
let g:tagbar_type_coffee = {
  \ 'kinds' : [
  \   'f:functions',
  \   'o:object'
  \ ],
  \ 'kind2scope' : {
  \  'f' : 'object',
  \   'o' : 'object'
  \},
  \ 'sro' : ".",
  \ 'ctagsbin' : 'coffeetags',
  \ 'ctagsargs' : '--include-vars '
  \}

" Markdown
let g:tagbar_type_markdown = {
  \ 'ctagstype' : 'markdown',
  \ 'kinds' : [
    \ 'h:Heading_L1',
    \ 'i:Heading_L2',
    \ 'k:Heading_L3'
  \ ]
\ }
