#!/usr/bin/bash

# Inspired greatly by Armin Ronacher's bashrc
# https://github.com/mitsuhiko/dotfiles/blob/master/bash/bashrc

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

DEFAULT_COLOR="[00;1m"
GRAY_COLOR="[37;1m"
PINK_COLOR="[35;1m"
GREEN_COLOR="[32;1m"
CYAN_COLOR="[36;1m"
ORANGE_COLOR="[33;1m"
RED_COLOR="[31;1m"
if [ `id -u` == '0' ]; then
  USER_COLOR=$RED_COLOR
else
  USER_COLOR=$ORANGE_COLOR
fi

VCPROMPT_EXECUTABLE=/usr/local/bin/vcprompt

function vcprompt_branch() {
  $VCPROMPT_EXECUTABLE -f $'%b'
}

function vcprompt_changed() {
  $VCPROMPT_EXECUTABLE -f $'%m%u'
}


function lastcommandfailed() {
  code=$?
  if [ $code != 0 ]; then
    echo -n $'\033[37;1m exited \033[31;1m'
    echo -n $code
    echo -n $'\033[37;1m'
  fi
}

function backgroundjobs() {
  jobs|python -c 'if 1:
    import sys
    items = ["\033[36;1m%s\033[37;1m" % x.split()[2]
             for x in sys.stdin.read().splitlines()]
    if items:
      if len(items) > 2:
        string = "%s, and %s" % (", ".join(items[:-1]), items[-1])
      else:
        string = ", ".join(items)
      print "\033[37;1m running %s" % string
  '
}

function searchreplace() {
  git grep -l "$1" | xargs sed -i "" "s/$1/$2/g"
}
export -f searchreplace

export BASEPROMPT='\[\e${GREEN_COLOR}\]\w \[\e${GRAY_COLOR}\]\[\e${GRAY_COLOR}\](\[\e${RED_COLOR}\]$(vcprompt_branch)\[\e${GREEN_COLOR}\]$(vcprompt_changed)\[\e${DEFAULT_COLOR}\])\[\e${GRAY_COLOR}\] \[\e${USER_COLOR}\]\u\[\e${DEFAULT_COLOR}\]'

export PROMPT="${BASEPROMPT}$ "
export PS1=$PROMPT

export TERM=rxvt
export GREP_OPTIONS='-i --color=auto' GREP_COLOR='1;32'

export CLICOLOR=1
if [ `uname` == "Darwin" ]; then
  export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
  export LC_CTYPE=en_US.utf-8
else
  alias ls='ls --color=auto -F'
fi
export IGNOREEOF=1
export LESS=FRSX

export LIBTOOLIZE=glibtoolize

# python
export PYTHONDONTWRITEBYTECODE=1

# Enable bash history
export HISTCONTROL=erasedups
TSIZE=50000
shopt -s histappend

export FALLBACK_DYLD_LIBRARY_PATH=/usr/local/lib

# These set up/down to do the history searching
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward

export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export SSL_CERT_FILE=/usr/local/etc/openssl/certs/cert.pem
export GOPATH=/Users/dzhou/go_code
export PATH="$PATH:$GOPATH/bin"
export SOLR_HOME=/usr/local/solr14
export PATH=".bundle/bin:$PATH"
eval "$(rbenv init -)"

alias c="clear"
alias l="ls"
alias less="less -R"
alias tree="tree -CAh"
alias gitlg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen%cn%Creset %Cblue%cr%Creset' --abbrev-commit --date=relative"
alias gits="git status"
alias gs="git status"
alias gd="git diff"
export GREP_OPTIONS='--color=auto -i'

#emacs aliases
alias emacs="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n -c -a /Applications/Emacs.app/Contents/MacOS/Emacs"
alias emacst="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -t -a /Applications/Emacs.app/Contents/MacOS/Emacs -nw"
alias et="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -t -a /Applications/Emacs.app/Contents/MacOS/Emacs -nw"
alias em="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n -a /Applications/Emacs.app/Contents/MacOS/Emacs"
alias e="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n -a /Applications/Emacs.app/Contents/MacOS/Emacs"

#sublime text aliases
alias slt='open -a "Sublime Text 2"'

#vim aliases
alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"

# set editor to vim
export EDITOR='vim'

#things for bash history to ignore
export HISTIGNORE="&:ls:[bf]g:exit:clear:c"

# solr setup
export SOLR_HOME=~/Documents/Vox/solr14

# rails aliases
alias bun="bundle"

# node and npm shit
export NODE_PATH="/usr/local/lib/node:/usr/local/lib/jsctags"
export PYTHONPATH="/usr/local/lib/python2.7/site-packages:/Library/Python/2.7/site-packages:~/Library/Application Support/Titanium:$PYTHONPATH"
export TITANIUM_SDK_VERSION="3.0.0.GA"
export TITANIUM_SDK=$HOME/Library/Application\ Support/Titanium/mobilesdk/osx/$TITANIUM_SDK_VERSION

export PROJECTS_PATH="/Users/dzhou/Vox"

# elastic search
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"


alias gg="git g"

alias be="bundle exec"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

alias npm-exec='PATH=$(npm bin):$PATH'
alias ne='PATH=$(npm bin):$PATH'

alias fstart="bundle exec foreman start -c all=1,web=0"
